# version: '3.8'

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE:-dev}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-abcd1234}
      PGDATA: /data/postgres
    volumes:
      - ./data/postgres:/data/postgres
    ports:
      - '5433:5432'
    # networks:
    #   - common
    restart: unless-stopped

  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   environment:
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_USERNAME: nestuser
  #     DB_PASSWORD: nestpass
  #     DB_NAME: nestdb

volumes:
  pgdata:
